//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa22.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeamQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fifa22.Data.Resources.TeamQueries", typeof(TeamQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from Player where TeamId = {0} ; delete from Team where Team_id = {0}.
        /// </summary>
        public static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top {0} Teamid as Team_id, sum(GoalCount) as TeamsGoals, Team_name, Team_group from PlayerEx group by Teamid, Team_name, Team_group  order by TeamsGoals desc.
        /// </summary>
        public static string GET_TEAM_BY_GOAL {
            get {
                return ResourceManager.GetString("GET_TEAM_BY_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Team_name, Team_group, Team_id from Team where Team_id = &apos;{0}&apos;.
        /// </summary>
        public static string GET_TEAM_BY_ID {
            get {
                return ResourceManager.GetString("GET_TEAM_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Team_name, Team_group, Team_id from Team where Team_group = &apos;{0}&apos;.
        /// </summary>
        public static string GET_TEAM_BY_NAME {
            get {
                return ResourceManager.GetString("GET_TEAM_BY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Team VALUES (&apos;{0}&apos;, &apos;{1}&apos;).
        /// </summary>
        public static string InsertTeam {
            get {
                return ResourceManager.GetString("InsertTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Team_name, Team_group, Team_id from Team.
        /// </summary>
        public static string TEAM_LIST {
            get {
                return ResourceManager.GetString("TEAM_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Team SET Team_name = &apos;{0}&apos;, Team_group = &apos;{1}&apos; where Team_id = &apos;{2}&apos;.
        /// </summary>
        public static string UpdateTeam {
            get {
                return ResourceManager.GetString("UpdateTeam", resourceCulture);
            }
        }
    }
}
